#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — the deploy path for M7. One stage() per step Ammar takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

# This wizard captures nothing into .env: production values are pasted straight
# into Vercel's dashboard, and local dev already works off `supabase start`.
# ENV_FILE points at a scratch path purely so `ask`'s "remember my last answer"
# lookup can never read the real .env / .env.local.
ENV_FILE="${TMPDIR:-/tmp}/pft-deploy-wizard.notes"

cd "$(dirname "${BASH_SOURCE[0]}")/.." || exit 1

REF_FILE="supabase/.temp/project-ref"
if [[ -f "$REF_FILE" ]]; then
  PROJECT_REF=$(tr -d '[:space:]' < "$REF_FILE")
else
  PROJECT_REF=""
fi

DASH="https://supabase.com/dashboard/project/${PROJECT_REF}"

banner "Personal Finance Tracker — ship M7 (deploy)"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Wake the paused Supabase project"
say "Your hosted project is INACTIVE — the free tier pauses a project after a"
say "stretch of no traffic. Every later stage needs it awake."
if [[ -z "$PROJECT_REF" ]]; then
  warn "No $REF_FILE — run 'npx supabase link' first, then re-run this wizard."
  exit 1
fi
note "project ref: $PROJECT_REF"
open_url "$DASH"
step "If you see a 'Project is paused' banner, click Restore / Resume."
step "Restoring takes a couple of minutes. Wait for the dashboard to go green."
pause "Press Enter once you've clicked Restore..."

say "Polling the API until it reports ACTIVE (Ctrl-C to bail out)..."
STATUS="UNKNOWN"
for attempt in $(seq 1 40); do
  STATUS=$(npx --yes supabase projects list --output-format json 2>/dev/null \
    | python3 -c "
import sys, json
try:
    data = json.load(sys.stdin)
except Exception:
    print('UNKNOWN'); raise SystemExit
for p in data.get('projects', []):
    if p.get('ref') == '$PROJECT_REF':
        print(p.get('status', 'UNKNOWN')); break
else:
    print('NOT_FOUND')
" 2>/dev/null || echo "UNKNOWN")
  printf '  attempt %-2s · status: %s\n' "$attempt" "$STATUS"
  [[ "$STATUS" == ACTIVE* ]] && break
  sleep 15
done
if [[ "$STATUS" != ACTIVE* ]]; then
  warn "Still not ACTIVE. Restoring can take longer — re-run this wizard later."
  SKIPPED+=("Supabase project restore (status was $STATUS)")
  confirm "Carry on anyway?" || exit 1
fi

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Push the database schema"
say "Both migrations have only ever been applied to local Docker Postgres."
say "Until this runs the hosted database is EMPTY, and the deployed app will"
say "fail on every single query."
note "supabase/migrations/ — 2 files"
say ""
# The CLI reports a blocked port as a vague timeout plus a misleading
# SUPABASE_DB_PASSWORD hint, so check reachability first and say what it is.
POOLER_HOST=$(sed -E 's#^[^@]*@([^:/]+).*#\1#' supabase/.temp/pooler-url 2>/dev/null || true)
if [[ -n "$POOLER_HOST" ]]; then
  if timeout 8 bash -c "exec 3<>/dev/tcp/${POOLER_HOST}/5432" 2>/dev/null; then
    say "✓ $POOLER_HOST:5432 is reachable"
  else
    warn "Can't reach $POOLER_HOST on port 5432 — your network is blocking"
    warn "outbound Postgres traffic (router, ISP, VPN or firewall). A password"
    warn "won't fix this. Try a phone hotspot with any VPN off, then re-run."
    confirm "Try the dry run anyway?" || exit 1
  fi
fi
say ""
say "First a dry run — this changes nothing:"
npx --yes supabase db push --linked --dry-run || warn "dry run failed — read the error above"
say ""
warn "The real push writes tables, RLS policies and triggers to the hosted DB."
if confirm "Apply these migrations to the hosted project now?"; then
  if npx --yes supabase db push --linked; then
    say "Verifying local and remote migration history line up..."
    npx --yes supabase migration list --linked || true
  else
    warn "Push failed — read the error above. Common cause: wrong DB password."
    SKIPPED+=("supabase db push (failed — re-run this wizard)")
  fi
else
  SKIPPED+=("supabase db push — hosted DB is still empty")
  note "Skipped. The deployed app cannot work until this runs."
fi

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Send your two local commits to GitHub"
say "Vercel deploys from GitHub, so it can only see commits that are up there."
say "Claude never runs git in this repo — this one is yours to run:"
say ""
git --no-pager log --oneline origin/main..main 2>/dev/null || true
say ""
if [[ -z "$(git log --oneline origin/main..main 2>/dev/null)" ]]; then
  say "Nothing pending — origin/main is already up to date."
else
  printf '      %sgit push origin main%s\n' "$BOLD" "$RESET"
  say ""
  say "Run that in another terminal now."
  pause "Press Enter once it's pushed..."
  if [[ -n "$(git log --oneline origin/main..main 2>/dev/null)" ]]; then
    warn "Still showing unpushed commits — did the push succeed?"
    SKIPPED+=("git push origin main")
  else
    say "✓ origin/main is up to date."
  fi
fi

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Import the repo into Vercel"
say "You have a Vercel account, but it isn't connected to this repo yet."
open_url "https://vercel.com/new"
step "Pick the 'personal-finances-tracker' repo and click Import."
step "Framework Preset should auto-detect as Next.js — leave it alone."
step "Leave Root Directory as ./ and don't override the build commands."
step "DON'T deploy yet — the env vars come next, and the first build needs them."
pause "Press Enter once the project is created..."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Give Vercel the three environment variables"
say "These are the HOSTED Supabase values — not the ones 'supabase start'"
say "prints for local dev."
open_url "${DASH}/settings/api-keys"
note "If that page 404s, it's under Project Settings → API / API Keys —"
note "Supabase has shuffled this page between dashboard versions."
say ""
say "Copy these three into Vercel → project → Settings → Environment Variables,"
say "each ticked for Production, Preview AND Development:"
say ""
step "NEXT_PUBLIC_SUPABASE_URL              → https://${PROJECT_REF}.supabase.co"
step "NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY  → the publishable / anon key (browser-safe)"
step "SUPABASE_SECRET_KEY                   → the secret / service_role key"
say ""
warn "The secret key bypasses RLS completely. It goes ONLY into Vercel's env"
warn "var screen — never into a commit, a doc, or a chat message."
pause "Press Enter once all three are saved in Vercel..."

say "Now trigger the first real deploy:"
step "Vercel → Deployments → Redeploy."
pause "Press Enter once the deploy goes green..."
ask VERCEL_DOMAIN "Paste the production domain (e.g. personal-finances-tracker.vercel.app):"
VERCEL_DOMAIN="${VERCEL_DOMAIN#https://}"
VERCEL_DOMAIN="${VERCEL_DOMAIN%/}"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Point Google OAuth at the new domain"
say "Sign-in fails until BOTH sides know the domain. No code change is needed:"
say "the callback already honours x-forwarded-host, and redirectTo is built"
say "from window.location.origin."
say ""
say "Side 1 — Google Cloud Console:"
open_url "https://console.cloud.google.com/apis/credentials"
step "Open your OAuth 2.0 Client ID."
step "Under 'Authorized redirect URIs', add exactly:"
note "    https://${PROJECT_REF}.supabase.co/auth/v1/callback"
note "  Google redirects to SUPABASE, not to Vercel — this is the one that"
note "  trips everyone up. It is NOT your vercel.app domain."
step "Save."
pause "Press Enter once saved..."

say ""
say "Side 2 — Supabase Auth URL configuration:"
open_url "${DASH}/auth/url-configuration"
step "Set Site URL to:  https://${VERCEL_DOMAIN}"
step "Under Redirect URLs, add:  https://${VERCEL_DOMAIN}/**"
step "Save."
pause "Press Enter once saved..."

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Verify the live site"
if [[ -n "${VERCEL_DOMAIN:-}" ]]; then
  say "An unauthenticated request to / should 307 to /auth/login — the same"
  say "check that proved the auth proxy worked locally."
  CODE=$(curl -s -o /dev/null -w '%{http_code}' "https://${VERCEL_DOMAIN}/" || echo "000")
  LOC=$(curl -s -o /dev/null -w '%{redirect_url}' "https://${VERCEL_DOMAIN}/" || echo "")
  say "  GET / → HTTP $CODE ${LOC:+(→ $LOC)}"
  case "$CODE" in
    307|302) say "  ✓ redirecting as expected" ;;
    200)     warn "200 — expected a redirect. Check the proxy/middleware config." ;;
    *)       warn "Unexpected $CODE — check the Vercel deploy logs." ;;
  esac
  say ""
  open_url "https://${VERCEL_DOMAIN}"
fi
step "Click 'Continue with Google' and sign in for real."
step "This is the FIRST time the Google round-trip has ever been exercised — it"
step "has only ever been stood in for by password sign-in against local Supabase."
step "On your phone: open the site → browser menu → 'Add to Home Screen'."
say ""
warn "If sign-in fails with redirect_uri_mismatch, the Google console URI from"
warn "stage 6 is wrong — it must end in .supabase.co/auth/v1/callback"
pause "Press Enter when you've signed in (or hit a wall worth reporting back)..."

finish
